/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdt4145.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.*;
import java.util.Properties;

public abstract class Connect {

    protected static Connection connection;

    public void DBConn() {

    }

    public static void connect() {

        try {

            Class.forName("com.mysql.jdbc.Driver");

            // Configuration for username and password
            Properties p = new Properties();
            p.put("user", "root");
            p.put("password", "password");

            connection = DriverManager.getConnection("jdbc:mysql://localhost/?characterEncoding=UTF-8", p);

        } catch (Exception e) {
            throw new RuntimeException("Unable to connect", e);
        }
    }
}
