/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdt4145.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.*;
import java.util.Properties;

public abstract class DBConn {
    protected static Connection connection;

    public void DBConn() {}

    public static void connect() {
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            // Configuration for username and password
            Properties p = new Properties();
            p.put("user", "root");
            p.put("password", "password");

            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/FilmDB", p);
            System.out.println("\u001B[32mConnection initialized!\u001B[0m\n");

        } catch (Exception e) {
            throw new RuntimeException("\\u001B[31mUnable to connect!\u001B[0m\n", e);
        }
    }
}
